import React, { Component } from 'react';
import Thing from './Thing';

class App extends Component {
  render() {
    return (
      <div className="App">
		<Thing/>

		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, animi? Deleniti neque voluptates odio impedit ut. Possimus tenetur repellendus voluptates quos odit. Beatae quasi rem deserunt impedit iste qui voluptas vero corrupti. Rem fugit consectetur, quam quaerat dolorem unde aliquid molestias labore aliquam nemo soluta minima? Debitis magni soluta aliquam exercitationem aliquid delectus saepe dolore unde nesciunt odit quia corporis labore temporibus corrupti fuga neque dolores harum eligendi, quis qui accusantium in amet? Doloribus consectetur reprehenderit nihil eveniet fugit blanditiis rerum vero molestias maxime, optio dolore tenetur deleniti soluta fuga, ex aliquid repellendus, maiores quae dolorem. Quae temporibus recusandae iure!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, animi? Deleniti neque voluptates odio impedit ut. Possimus tenetur repellendus voluptates quos odit. Beatae quasi rem deserunt impedit iste qui voluptas vero corrupti. Rem fugit consectetur, quam quaerat dolorem unde aliquid molestias labore aliquam nemo soluta minima? Debitis magni soluta aliquam exercitationem aliquid delectus saepe dolore unde nesciunt odit quia corporis labore temporibus corrupti fuga neque dolores harum eligendi, quis qui accusantium in amet? Doloribus consectetur reprehenderit nihil eveniet fugit blanditiis rerum vero molestias maxime, optio dolore tenetur deleniti soluta fuga, ex aliquid repellendus, maiores quae dolorem. Quae temporibus recusandae iure!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, animi? Deleniti neque voluptates odio impedit ut. Possimus tenetur repellendus voluptates quos odit. Beatae quasi rem deserunt impedit iste qui voluptas vero corrupti. Rem fugit consectetur, quam quaerat dolorem unde aliquid molestias labore aliquam nemo soluta minima? Debitis magni soluta aliquam exercitationem aliquid delectus saepe dolore unde nesciunt odit quia corporis labore temporibus corrupti fuga neque dolores harum eligendi, quis qui accusantium in amet? Doloribus consectetur reprehenderit nihil eveniet fugit blanditiis rerum vero molestias maxime, optio dolore tenetur deleniti soluta fuga, ex aliquid repellendus, maiores quae dolorem. Quae temporibus recusandae iure!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, animi? Deleniti neque voluptates odio impedit ut. Possimus tenetur repellendus voluptates quos odit. Beatae quasi rem deserunt impedit iste qui voluptas vero corrupti. Rem fugit consectetur, quam quaerat dolorem unde aliquid molestias labore aliquam nemo soluta minima? Debitis magni soluta aliquam exercitationem aliquid delectus saepe dolore unde nesciunt odit quia corporis labore temporibus corrupti fuga neque dolores harum eligendi, quis qui accusantium in amet? Doloribus consectetur reprehenderit nihil eveniet fugit blanditiis rerum vero molestias maxime, optio dolore tenetur deleniti soluta fuga, ex aliquid repellendus, maiores quae dolorem. Quae temporibus recusandae iure!</p>
		<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, animi? Deleniti neque voluptates odio impedit ut. Possimus tenetur repellendus voluptates quos odit. Beatae quasi rem deserunt impedit iste qui voluptas vero corrupti. Rem fugit consectetur, quam quaerat dolorem unde aliquid molestias labore aliquam nemo soluta minima? Debitis magni soluta aliquam exercitationem aliquid delectus saepe dolore unde nesciunt odit quia corporis labore temporibus corrupti fuga neque dolores harum eligendi, quis qui accusantium in amet? Doloribus consectetur reprehenderit nihil eveniet fugit blanditiis rerum vero molestias maxime, optio dolore tenetur deleniti soluta fuga, ex aliquid repellendus, maiores quae dolorem. Quae temporibus recusandae iure!</p>
      </div>
    );
  }
}

export default App;
